/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.resourcemanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.enterprise.HospitalEnterprise;
import com.neu.phmis.business.request.DeviceRequest;
import com.neu.phmis.business.request.Request;
import com.neu.phmis.business.request.SurgeryRequest;
import com.neu.phmis.business.user.ResourceManager;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.userinterface.MainFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ManageResourceRequestsPanel extends javax.swing.JPanel {

    private Ecosystem ecosystem;
    private HospitalEnterprise hospitalEnterprise;
    private ResourceManager resourceManager;

    public static ManageResourceRequestsPanel manageResourceRequestsPanel;

    /**
     * Creates new form ManageRequests
     */
    public ManageResourceRequestsPanel(HospitalEnterprise hospitalEnterprise,
            ResourceManager resourceManager) {

        initComponents();

        this.hospitalEnterprise = hospitalEnterprise;
        this.resourceManager = resourceManager;
        ecosystem = Ecosystem.getInstance();
        manageResourceRequestsPanel = this;

        populateTables();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        webPanel1 = new com.alee.laf.panel.WebPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        surgeryRequestTbl = new com.alee.laf.table.WebTable();
        viewRequestBtn = new com.alee.laf.button.WebButton();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deviceRequestTbl = new com.alee.laf.table.WebTable();
        createRequestBtn = new com.alee.laf.button.WebButton();
        viewRequestBtn1 = new com.alee.laf.button.WebButton();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        surgeryRequestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Doctor", "Created On", "Scheduling Dates", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        surgeryRequestTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(surgeryRequestTbl);

        viewRequestBtn.setForeground(new java.awt.Color(0, 0, 255));
        viewRequestBtn.setText("View");
        viewRequestBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel1Layout = new javax.swing.GroupLayout(webPanel1);
        webPanel1.setLayout(webPanel1Layout);
        webPanel1Layout.setHorizontalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        webPanel1Layout.setVerticalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Surgery Request", webPanel1);

        deviceRequestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Created On", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        deviceRequestTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(deviceRequestTbl);

        createRequestBtn.setForeground(new java.awt.Color(0, 0, 255));
        createRequestBtn.setText("Create Request");
        createRequestBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRequestBtnActionPerformed(evt);
            }
        });

        viewRequestBtn1.setForeground(new java.awt.Color(0, 0, 255));
        viewRequestBtn1.setText("View");
        viewRequestBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewRequestBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addComponent(createRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewRequestBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewRequestBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Device Request", webPanel2);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void createRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRequestBtnActionPerformed

        try {

            CreateDeviceRequest createDeviceRequest
                    = new CreateDeviceRequest(MainFrame.mainFrame, true,
                            hospitalEnterprise, resourceManager, this);
            createDeviceRequest.setVisible(true);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_createRequestBtnActionPerformed

    private void viewRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestBtnActionPerformed

        try {

            int selectedRow = surgeryRequestTbl.getSelectedRow();

            if (selectedRow >= 0) {

                SurgeryRequest surgeryRequest
                        = (SurgeryRequest) surgeryRequestTbl
                        .getValueAt(selectedRow, 0);
                ViewScheduleRequestDialog viewScheduleRequestDialog
                        = new ViewScheduleRequestDialog(MainFrame.mainFrame,
                                true, surgeryRequest, resourceManager);
                viewScheduleRequestDialog.setVisible(true);

            } else {
                WebOptionPane.showMessageDialog(null,
                        "No Request Selected", "Warning",
                        WebOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_viewRequestBtnActionPerformed

    private void viewRequestBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestBtn1ActionPerformed

        try {

            int selectedRow = deviceRequestTbl.getSelectedRow();

            if (selectedRow >= 0) {
                ViewDeviceRequestDialog viewDeviceRequestDialog
                        = new ViewDeviceRequestDialog(MainFrame.mainFrame, true,
                                (DeviceRequest) deviceRequestTbl
                                .getValueAt(selectedRow, 0));
                viewDeviceRequestDialog.setVisible(true);
            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_viewRequestBtn1ActionPerformed


    /* ---------------------------------------------------------------------- */
    /*
     Populate requests in the tables
    
     Parameters: NONE
    
     Returns: NONE
     */
    public void populateTables() {

        try {

            DefaultTableModel defaultTableModel
                    = (DefaultTableModel) surgeryRequestTbl.getModel();
            defaultTableModel.setRowCount(0);

            SurgeryRequest surgeryRequest = null;
            Object row[];
            for (Request request : hospitalEnterprise.getSurgeryRequestQueue()
                    .getRequestList()) {

                surgeryRequest = (SurgeryRequest) request;
                row = new Object[5];
                row[0] = surgeryRequest;
                row[1] = surgeryRequest.getSurgicalOperation().getDoctor();
                row[2] = CommonUtil.changeDateFormat(surgeryRequest
                        .getCreatedOn(), "dd MMM, yyyy");
                row[3] = CommonUtil.changeDateFormat(surgeryRequest
                        .getStartDate(), "dd MMM, yyyy") + " - " + CommonUtil
                        .changeDateFormat(surgeryRequest.getEndDate(), "dd "
                                + "MMM, yyyy");
                row[4] = surgeryRequest.getStatus();
                defaultTableModel.addRow(row);

            }

            defaultTableModel = (DefaultTableModel) deviceRequestTbl.getModel();
            defaultTableModel.setRowCount(0);

            DeviceRequest deviceRequest = null;
            for (Request request : resourceManager.getDeviceRequestQueue()
                    .getRequestList()) {

                deviceRequest = (DeviceRequest) request;
                row = new Object[3];
                row[0] = deviceRequest;
                row[1] = CommonUtil.changeDateFormat(deviceRequest
                        .getCreatedOn(), "dd MMM, yyyy");
                row[2] = deviceRequest.getStatus();
                defaultTableModel.addRow(row);

            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton createRequestBtn;
    private com.alee.laf.table.WebTable deviceRequestTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.alee.laf.table.WebTable surgeryRequestTbl;
    private com.alee.laf.button.WebButton viewRequestBtn;
    private com.alee.laf.button.WebButton viewRequestBtn1;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    // End of variables declaration//GEN-END:variables
}
