/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.resourcemanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.request.SurgeryRequest;
import com.neu.phmis.business.user.ResourceManager;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.business.util.MailUtil;
import com.neu.phmis.userinterface.MainFrame;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ViewScheduleRequestDialog extends javax.swing.JDialog {

    private SurgeryRequest surgeryRequest;
    private ResourceManager resourceManager;
    private Ecosystem ecosystem;

    /**
     * Creates new form ViewScheduleRequestDialog
     */
    public ViewScheduleRequestDialog(java.awt.Frame parent, boolean modal,
            SurgeryRequest surgeryRequest, ResourceManager resourceManager) {

        super(parent, modal);
        initComponents();
        this.surgeryRequest = surgeryRequest;
        this.resourceManager = resourceManager;
        this.setLocationRelativeTo(null);
        ecosystem = Ecosystem.getInstance();

        requestIdLbl.setText(surgeryRequest.getRequestId());
        doctorLbl.setText(surgeryRequest.getSentBy().getFullName());
        creationDateLbl.setText(CommonUtil.changeDateFormat(surgeryRequest
                .getCreatedOn(), "dd MMM, yyyy"));
        statusLbl.setText(surgeryRequest.getStatus());
        surgeryTypeLbl.setText(surgeryRequest.getSurgicalOperation()
                .getSurgeryType());
        patientNameLbl.setText(surgeryRequest.getSurgicalOperation()
                .getPatientName());
        fromDateLbl.setText(CommonUtil.changeDateFormat(surgeryRequest
                .getStartDate(), "dd MMM, yyyy"));
        toDateLbl.setText(CommonUtil.changeDateFormat(surgeryRequest
                .getEndDate(), "dd MMM, yyyy"));
        noOfStaffLbl.setText(String.valueOf(surgeryRequest.getNoOfStaff()));

        DefaultTableModel defaultTableModel = (DefaultTableModel) productListTbl
                .getModel();

        Object row[] = null;
        for (String device : surgeryRequest.getDeviceList()) {
            row = new Object[1];
            row[0] = device;
            defaultTableModel.addRow(row);
        }

        if (surgeryRequest.getStatus().equals(SurgeryRequest.STATUS_PENDING)) {
            processedByTitleLbl.setVisible(false);
            processedByLbl.setVisible(false);
            processedOnLbl.setVisible(false);
            processedOnTitleLbl.setVisible(false);
        } else {
            processedByLbl.setText(surgeryRequest.getProcessedBy()
                    .getFullName());
            processedOnLbl.setText(CommonUtil.changeDateFormat(surgeryRequest
                    .getProcessedOn(), "dd MMM, yyyy"));
        }

        if (surgeryRequest.getSpecialInstruction().isEmpty()) {
            specInstrucTitleLbl.setVisible(false);
            specialInstructionLbl.setVisible(false);
        } else {
            specialInstructionLbl.setText(surgeryRequest
                    .getSpecialInstruction());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelBtn = new com.alee.laf.button.WebButton();
        statusLbl = new com.alee.laf.label.WebLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        webLabel9 = new com.alee.laf.label.WebLabel();
        requestIdLbl = new com.alee.laf.label.WebLabel();
        webLabel8 = new com.alee.laf.label.WebLabel();
        creationDateLbl = new com.alee.laf.label.WebLabel();
        processedOnLbl = new com.alee.laf.label.WebLabel();
        processedOnTitleLbl = new com.alee.laf.label.WebLabel();
        processedByLbl = new com.alee.laf.label.WebLabel();
        processedByTitleLbl = new com.alee.laf.label.WebLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productListTbl = new com.alee.laf.table.WebTable();
        doctorLbl = new com.alee.laf.label.WebLabel();
        webLabel7 = new com.alee.laf.label.WebLabel();
        processBtn = new com.alee.laf.button.WebButton();
        webLabel1 = new com.alee.laf.label.WebLabel();
        fromDateLbl = new com.alee.laf.label.WebLabel();
        webLabel10 = new com.alee.laf.label.WebLabel();
        processedByTitleLbl1 = new com.alee.laf.label.WebLabel();
        toDateLbl = new com.alee.laf.label.WebLabel();
        processedOnTitleLbl1 = new com.alee.laf.label.WebLabel();
        webLabel11 = new com.alee.laf.label.WebLabel();
        patientNameLbl = new com.alee.laf.label.WebLabel();
        noOfStaffLbl = new com.alee.laf.label.WebLabel();
        webLabel12 = new com.alee.laf.label.WebLabel();
        surgeryTypeLbl = new com.alee.laf.label.WebLabel();
        processedOnTitleLbl2 = new com.alee.laf.label.WebLabel();
        specInstrucTitleLbl = new com.alee.laf.label.WebLabel();
        specialInstructionLbl = new com.alee.extended.label.WebMultiLineLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancelBtn.setForeground(new java.awt.Color(0, 0, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        statusLbl.setText("<Status>");
        statusLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel5.setText("Request ID:");
        webLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel9.setText("Status:");
        webLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        requestIdLbl.setText("<Request ID>");
        requestIdLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel8.setText("Created On:");
        webLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        creationDateLbl.setText("<Creation Date>");
        creationDateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnLbl.setText("<Processed On>");
        processedOnLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnTitleLbl.setText("Processed On:");
        processedOnTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByLbl.setText("<Processed By>");
        processedByLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByTitleLbl.setText("Processed By:");
        processedByTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        productListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productListTbl);

        doctorLbl.setText("<Doctor>");
        doctorLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel7.setText("Doctor:");
        webLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processBtn.setForeground(new java.awt.Color(0, 0, 255));
        processBtn.setText("Process");
        processBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        webLabel1.setForeground(new java.awt.Color(0, 51, 255));
        webLabel1.setText("Surgery Schedule Request");
        webLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        fromDateLbl.setText("<From Date>");
        fromDateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel10.setText("From Date:");
        webLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByTitleLbl1.setText("To Date:");
        processedByTitleLbl1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        toDateLbl.setText("<To Date>");
        toDateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnTitleLbl1.setText("Staff Required:");
        processedOnTitleLbl1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel11.setText("Surgery:");
        webLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        patientNameLbl.setText("<Patient Name>");
        patientNameLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        noOfStaffLbl.setText("<No of Staff>");
        noOfStaffLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel12.setText("Patient Name:");
        webLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        surgeryTypeLbl.setText("<Type>");
        surgeryTypeLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnTitleLbl2.setText("Devices Required:");
        processedOnTitleLbl2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        specInstrucTitleLbl.setText("Special Instructions:");
        specInstrucTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        specialInstructionLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specInstrucTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedByTitleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(surgeryTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedOnTitleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noOfStaffLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processedOnTitleLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(specialInstructionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creationDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doctorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(requestIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creationDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surgeryTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processedByTitleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processedOnTitleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noOfStaffLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(processedOnTitleLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(specInstrucTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialInstructionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed

        try {

            if (surgeryRequest.getStatus()
                    .equals(SurgeryRequest.STATUS_PENDING)) {

                String message = "Click YES if you want to schedule the "
                        + "surgery, NO if you want to decline the request and "
                        + "CANCEL if no action has to be taken.";

                int ans = WebOptionPane.showConfirmDialog(null, message,
                        "Action is needed", WebOptionPane.YES_NO_CANCEL_OPTION);

                if (ans == WebOptionPane.YES_OPTION) {

                    this.dispose();

                    ScheduleSurgeryDialog scheduleSurgeryDialog
                            = new ScheduleSurgeryDialog(MainFrame.mainFrame,
                                    true, surgeryRequest, resourceManager);
                    scheduleSurgeryDialog.setVisible(true);

                } else if (ans == WebOptionPane.NO_OPTION) {

                    surgeryRequest.setStatus(SurgeryRequest.STATUS_FAILED);
                    surgeryRequest.setProcessedBy(resourceManager);
                    surgeryRequest.setProcessedOn(new Date());

                    ManageResourceRequestsPanel.manageResourceRequestsPanel
                            .populateTables();
                    CommonUtil.saveChanges(ecosystem);
                    this.dispose();

                    MailUtil mailUtil = new MailUtil(surgeryRequest.getSentBy()
                            .getEmailId());
                    StringBuffer stringBuffer = new StringBuffer();
                    stringBuffer.append(surgeryRequest.getSentBy())
                            .append(",\n Your request sent on ")
                            .append(CommonUtil.changeDateFormat(surgeryRequest
                                            .getCreatedOn(), "dd MMM, yyyy"))
                            .append("for scheduling surgery could not be "
                                    + "processed due to lack of resource "
                                    + "availability in the given date range");
                    mailUtil.setEmailSubject("Request Update Notification");
                    mailUtil.sendEmail();

                }

            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_processBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewScheduleRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewScheduleRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewScheduleRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewScheduleRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewScheduleRequestDialog dialog
                        = new ViewScheduleRequestDialog(
                                new javax.swing.JFrame(), true, surgeryRequest,
                                resourceManager);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton cancelBtn;
    private com.alee.laf.label.WebLabel creationDateLbl;
    private com.alee.laf.label.WebLabel doctorLbl;
    private com.alee.laf.label.WebLabel fromDateLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private com.alee.laf.label.WebLabel noOfStaffLbl;
    private com.alee.laf.label.WebLabel patientNameLbl;
    private com.alee.laf.button.WebButton processBtn;
    private com.alee.laf.label.WebLabel processedByLbl;
    private com.alee.laf.label.WebLabel processedByTitleLbl;
    private com.alee.laf.label.WebLabel processedByTitleLbl1;
    private com.alee.laf.label.WebLabel processedOnLbl;
    private com.alee.laf.label.WebLabel processedOnTitleLbl;
    private com.alee.laf.label.WebLabel processedOnTitleLbl1;
    private com.alee.laf.label.WebLabel processedOnTitleLbl2;
    private com.alee.laf.table.WebTable productListTbl;
    private com.alee.laf.label.WebLabel requestIdLbl;
    private com.alee.laf.label.WebLabel specInstrucTitleLbl;
    private com.alee.extended.label.WebMultiLineLabel specialInstructionLbl;
    private com.alee.laf.label.WebLabel statusLbl;
    private com.alee.laf.label.WebLabel surgeryTypeLbl;
    private com.alee.laf.label.WebLabel toDateLbl;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel10;
    private com.alee.laf.label.WebLabel webLabel11;
    private com.alee.laf.label.WebLabel webLabel12;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel7;
    private com.alee.laf.label.WebLabel webLabel8;
    private com.alee.laf.label.WebLabel webLabel9;
    // End of variables declaration//GEN-END:variables
}
