/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.resourcemanager;

import com.neu.phmis.business.request.DeviceRequest;
import com.neu.phmis.business.util.CommonUtil;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ViewDeviceRequestDialog extends javax.swing.JDialog {

    private DeviceRequest deviceRequest;

    /**
     * Creates new form ViewDeviceRequestDialog
     */
    public ViewDeviceRequestDialog(java.awt.Frame parent, boolean modal,
            DeviceRequest deviceRequest) {

        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.deviceRequest = deviceRequest;

        requestIdLbl.setText(deviceRequest.getRequestId());
        creationDateLbl.setText(CommonUtil.changeDateFormat(deviceRequest
                .getCreatedOn(), "dd MMM, yyyy"));
        statusLbl.setText(deviceRequest.getStatus());

        DefaultTableModel defaultTableModel = (DefaultTableModel) productListTbl
                .getModel();

        Object row[] = null;
        for (String device : deviceRequest.getDeviceList()) {
            row = new Object[1];
            row[0] = device;
            defaultTableModel.addRow(row);
        }

        if (deviceRequest.getStatus().equals(DeviceRequest.STATUS_PENDING)) {
            processedByTitleLbl.setVisible(false);
            processedByLbl.setVisible(false);
            processedOnLbl.setVisible(false);
            processedOnTitleLbl.setVisible(false);
        } else {
            processedByLbl.setText(deviceRequest.getProcessedBy()
                    .getFullName());
            processedOnLbl.setText(CommonUtil.changeDateFormat(deviceRequest
                    .getProcessedOn(), "dd MMM, yyyy"));
        }

        if (deviceRequest.getSpecialInstruction().isEmpty()) {
            specInstrucTitleLbl.setVisible(false);
            specialInstructionLbl.setVisible(false);
        } else {
            specialInstructionLbl.setText(deviceRequest
                    .getSpecialInstruction());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webLabel8 = new com.alee.laf.label.WebLabel();
        requestIdLbl = new com.alee.laf.label.WebLabel();
        webLabel9 = new com.alee.laf.label.WebLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        statusLbl = new com.alee.laf.label.WebLabel();
        processedOnTitleLbl = new com.alee.laf.label.WebLabel();
        processedByLbl = new com.alee.laf.label.WebLabel();
        creationDateLbl = new com.alee.laf.label.WebLabel();
        processedOnLbl = new com.alee.laf.label.WebLabel();
        processedByTitleLbl = new com.alee.laf.label.WebLabel();
        webLabel1 = new com.alee.laf.label.WebLabel();
        processedOnTitleLbl2 = new com.alee.laf.label.WebLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productListTbl = new com.alee.laf.table.WebTable();
        specInstrucTitleLbl = new com.alee.laf.label.WebLabel();
        specialInstructionLbl = new com.alee.extended.label.WebMultiLineLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        webLabel8.setText("Created On:");
        webLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        requestIdLbl.setText("<Request ID>");
        requestIdLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel9.setText("Status:");
        webLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel5.setText("Request ID:");
        webLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        statusLbl.setText("<Status>");
        statusLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnTitleLbl.setText("Processed On:");
        processedOnTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByLbl.setText("<Processed By>");
        processedByLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        creationDateLbl.setText("<Creation Date>");
        creationDateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnLbl.setText("<Processed On>");
        processedOnLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByTitleLbl.setText("Processed By:");
        processedByTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel1.setForeground(new java.awt.Color(0, 51, 255));
        webLabel1.setText("Device Request");
        webLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        processedOnTitleLbl2.setText("Devices Requested:");
        processedOnTitleLbl2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        productListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productListTbl);

        specInstrucTitleLbl.setText("Special Instructions:");
        specInstrucTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        specialInstructionLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processedOnTitleLbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creationDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(requestIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specInstrucTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(specialInstructionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creationDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(processedOnTitleLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(specInstrucTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialInstructionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDeviceRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDeviceRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDeviceRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDeviceRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewDeviceRequestDialog dialog
                        = new ViewDeviceRequestDialog(new javax.swing.JFrame(),
                                true, deviceRequest);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.label.WebLabel creationDateLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private com.alee.laf.label.WebLabel processedByLbl;
    private com.alee.laf.label.WebLabel processedByTitleLbl;
    private com.alee.laf.label.WebLabel processedOnLbl;
    private com.alee.laf.label.WebLabel processedOnTitleLbl;
    private com.alee.laf.label.WebLabel processedOnTitleLbl2;
    private com.alee.laf.table.WebTable productListTbl;
    private com.alee.laf.label.WebLabel requestIdLbl;
    private com.alee.laf.label.WebLabel specInstrucTitleLbl;
    private com.alee.extended.label.WebMultiLineLabel specialInstructionLbl;
    private com.alee.laf.label.WebLabel statusLbl;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel8;
    private com.alee.laf.label.WebLabel webLabel9;
    // End of variables declaration//GEN-END:variables
}
