/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.inventorymanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.inventory.InventoryItem;
import com.neu.phmis.business.util.CommonUtil;

/**
 *
 * @author Vineet
 */
public class ChangeConditionDialog extends javax.swing.JDialog {

    private Ecosystem ecosystem;
    private InventoryItem inventoryItem;
    private ManageInventoryItemsPanel manageInventoryItemsPanel;

    /**
     * Creates new form changeConditionDialog
     */
    public ChangeConditionDialog(java.awt.Frame parent, boolean modal,
            InventoryItem inventoryItem,
            ManageInventoryItemsPanel manageInventoryItemsPanel) {

        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        ecosystem = Ecosystem.getInstance();
        this.inventoryItem = inventoryItem;
        this.manageInventoryItemsPanel = manageInventoryItemsPanel;

        conditionCombo.addItem(InventoryItem.CONDITION_GOOD);
        conditionCombo.addItem(InventoryItem.CONDITION_WORKING);
        conditionCombo.addItem(InventoryItem.CONDITION_DAMAGED);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conditionCombo = new com.alee.laf.combobox.WebComboBox();
        viewRequestBtn = new com.alee.laf.button.WebButton();
        viewRequestBtn1 = new com.alee.laf.button.WebButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        viewRequestBtn.setForeground(new java.awt.Color(0, 0, 255));
        viewRequestBtn.setText("Change");
        viewRequestBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestBtnActionPerformed(evt);
            }
        });

        viewRequestBtn1.setForeground(new java.awt.Color(0, 0, 255));
        viewRequestBtn1.setText("Cancel");
        viewRequestBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewRequestBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conditionCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewRequestBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(conditionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewRequestBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestBtnActionPerformed

        try {

            inventoryItem.setCondition((String) conditionCombo
                    .getSelectedItem());
            manageInventoryItemsPanel.populateTable();
            CommonUtil.saveChanges(ecosystem);
            this.dispose();

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewRequestBtnActionPerformed

    private void viewRequestBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestBtn1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_viewRequestBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeConditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeConditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeConditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeConditionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeConditionDialog dialog
                        = new ChangeConditionDialog(new javax.swing.JFrame(),
                                true, inventoryItem, manageInventoryItemsPanel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.combobox.WebComboBox conditionCombo;
    private com.alee.laf.button.WebButton viewRequestBtn;
    private com.alee.laf.button.WebButton viewRequestBtn1;
    // End of variables declaration//GEN-END:variables
}
