/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.inventorymanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.enterprise.WarehouseEnterprise;
import com.neu.phmis.business.user.InventoryManager;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.userinterface.LoginPanel;
import com.neu.phmis.userinterface.MainFrame;

/**
 *
 * @author Vineet
 */
public class InventoryManagerDashboardPanel extends javax.swing.JPanel {

    private Ecosystem ecosystem;
    private InventoryManager inventoryManager;

    /**
     * Creates new form InventoryManagerDashboardPanel
     */
    public InventoryManagerDashboardPanel(InventoryManager inventoryManager) {
        initComponents();
        ecosystem = Ecosystem.getInstance();
        this.inventoryManager = inventoryManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webPanel2 = new com.alee.laf.panel.WebPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        webPanel3 = new com.alee.laf.panel.WebPanel();
        inventoryBtn = new com.alee.laf.button.WebButton();
        requestsBtn = new com.alee.laf.button.WebButton();
        logoutBtn = new com.alee.laf.button.WebButton();
        inventoryContainer = new com.alee.laf.panel.WebPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        inventoryBtn.setForeground(new java.awt.Color(0, 0, 255));
        inventoryBtn.setText("Inventory");
        inventoryBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });

        requestsBtn.setForeground(new java.awt.Color(0, 0, 255));
        requestsBtn.setText("Requests");
        requestsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        requestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestsBtnActionPerformed(evt);
            }
        });

        logoutBtn.setForeground(new java.awt.Color(0, 0, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel3Layout = new javax.swing.GroupLayout(webPanel3);
        webPanel3.setLayout(webPanel3Layout);
        webPanel3Layout.setHorizontalGroup(
            webPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requestsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        webPanel3Layout.setVerticalGroup(
            webPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(webPanel3);

        inventoryContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(inventoryContainer);

        webPanel2.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(webPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed

        try {

            ManageInventoryItemsPanel manageInventoryPanel
                    = new ManageInventoryItemsPanel(inventoryManager);
            CommonUtil.insertNewPanel(inventoryContainer,
                    "Manage Inventory Panel", manageInventoryPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_inventoryBtnActionPerformed

    private void requestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsBtnActionPerformed

        try {
            ManageInventoryRequestsPanel manageInventoryRequestsPanel
                    = new ManageInventoryRequestsPanel(
                            (WarehouseEnterprise) inventoryManager.getEnterprise(),
                            inventoryManager, inventoryContainer);
            CommonUtil.insertNewPanel(inventoryContainer, "Manage Inventory",
                    manageInventoryRequestsPanel, null);
        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_requestsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed

        try {
            CommonUtil.saveChanges(ecosystem);
            LoginPanel loginPanel
                    = new LoginPanel(MainFrame.mainFrame.getContainer(),
                            ecosystem);
            CommonUtil.insertNewPanel(MainFrame.mainFrame.getContainer(),
                    "Login Panel", loginPanel, this);
        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton inventoryBtn;
    private com.alee.laf.panel.WebPanel inventoryContainer;
    private javax.swing.JSplitPane jSplitPane1;
    private com.alee.laf.button.WebButton logoutBtn;
    private com.alee.laf.button.WebButton requestsBtn;
    private com.alee.laf.panel.WebPanel webPanel2;
    private com.alee.laf.panel.WebPanel webPanel3;
    // End of variables declaration//GEN-END:variables
}
