/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.inventorymanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.inventory.InventoryItem;
import com.neu.phmis.business.inventory.MaintenanceReport;
import com.neu.phmis.business.inventory.Product;
import com.neu.phmis.business.schedule.Schedule;
import com.neu.phmis.business.user.InventoryManager;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.userinterface.MainFrame;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ViewItemDetails extends javax.swing.JDialog {

    private InventoryItem inventoryItem;
    private String deviceStatus;
    private InventoryManager inventoryManager;

    /**
     * Creates new form ViewItemDetails
     */
    public ViewItemDetails(java.awt.Frame parent, boolean modal,
            InventoryItem inventoryItem, String deviceStatus,
            InventoryManager inventoryManager) {

        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        this.inventoryItem = inventoryItem;
        this.deviceStatus = deviceStatus;
        this.inventoryManager = inventoryManager;

        serialNoLbl.setText(inventoryItem.getSerialNumber());
        deviceLbl.setText(inventoryItem.getProduct().getProductName());
        conditionLbl.setText(inventoryItem.getCondition());
        currentLocationLbl.setText(deviceStatus);
        addedOnLbl.setText(CommonUtil.changeDateFormat(inventoryItem
                .getAddedOn(), "dd MMM, yyyy"));

        DefaultTableModel defaultTableModel
                = (DefaultTableModel) usageTbl.getModel();

        Object row[];
        for (Schedule schedule : inventoryItem.getItemSchedule()
                .getScheduleList()) {
            if (schedule.getScheduleDate().before(new Date())) {
                row = new Object[2];
                row[0] = schedule;
                row[1] = schedule.getHospitalEnterprise() == null
                        ? "Maintenance" : schedule.getHospitalEnterprise();
                defaultTableModel.addRow(row);
            }
        }

        defaultTableModel = (DefaultTableModel) scheduleTbl.getModel();

        for (Schedule schedule : inventoryItem.getItemSchedule()
                .getScheduleList()) {
            if (schedule.getScheduleDate().after(new Date())) {
                row = new Object[2];
                row[0] = schedule;
                row[1] = schedule.getHospitalEnterprise() == null
                        ? "Maintenance" : schedule.getHospitalEnterprise();
                defaultTableModel.addRow(row);
            }
        }

        Product product = inventoryItem.getProduct();

        productNameLbl.setText(product.getProductName());
        productIdLbl.setText(product.getProductId());
        productCostLbl.setText("$ " + product.getProductCost());

        descriptionTxt.setText(product.getProductDescription());

        populateReports();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        webPanel1 = new com.alee.laf.panel.WebPanel();
        webLabel10 = new com.alee.laf.label.WebLabel();
        serialNoLbl = new com.alee.laf.label.WebLabel();
        webLabel11 = new com.alee.laf.label.WebLabel();
        deviceLbl = new com.alee.laf.label.WebLabel();
        webLabel12 = new com.alee.laf.label.WebLabel();
        conditionLbl = new com.alee.laf.label.WebLabel();
        webLabel13 = new com.alee.laf.label.WebLabel();
        currentLocationLbl = new com.alee.laf.label.WebLabel();
        webLabel14 = new com.alee.laf.label.WebLabel();
        addedOnLbl = new com.alee.laf.label.WebLabel();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usageTbl = new com.alee.laf.table.WebTable();
        addReportBtn = new com.alee.laf.button.WebButton();
        webPanel3 = new com.alee.laf.panel.WebPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        scheduleTbl = new com.alee.laf.table.WebTable();
        webPanel4 = new com.alee.laf.panel.WebPanel();
        webLabel24 = new com.alee.laf.label.WebLabel();
        productNameLbl = new com.alee.laf.label.WebLabel();
        webLabel25 = new com.alee.laf.label.WebLabel();
        webLabel26 = new com.alee.laf.label.WebLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTxt = new com.alee.laf.text.WebTextArea();
        productIdLbl = new com.alee.laf.label.WebLabel();
        productCostLbl = new com.alee.laf.label.WebLabel();
        webPanel5 = new com.alee.laf.panel.WebPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reportTbl = new com.alee.laf.table.WebTable();
        webLabel15 = new com.alee.laf.label.WebLabel();
        maintenanceDateLbl = new com.alee.laf.label.WebLabel();
        webLabel16 = new com.alee.laf.label.WebLabel();
        reportDateLbl = new com.alee.laf.label.WebLabel();
        webLabel17 = new com.alee.laf.label.WebLabel();
        createdByLbl = new com.alee.laf.label.WebLabel();
        webLabel18 = new com.alee.laf.label.WebLabel();
        costLbl = new com.alee.laf.label.WebLabel();
        webLabel19 = new com.alee.laf.label.WebLabel();
        reportLbl = new com.alee.extended.label.WebMultiLineLabel();
        webLabel20 = new com.alee.laf.label.WebLabel();
        reportIdLbl = new com.alee.laf.label.WebLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        webLabel10.setText("Serial No:");
        webLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        serialNoLbl.setText("<No of Staff>");
        serialNoLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel11.setText("Device:");
        webLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        deviceLbl.setText("<No of Staff>");
        deviceLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel12.setText("Condition:");
        webLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        conditionLbl.setText("<No of Staff>");
        conditionLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel13.setText("Current Location:");
        webLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        currentLocationLbl.setText("<No of Staff>");
        currentLocationLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel14.setText("Added On:");
        webLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        addedOnLbl.setText("<No of Staff>");
        addedOnLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout webPanel1Layout = new javax.swing.GroupLayout(webPanel1);
        webPanel1.setLayout(webPanel1Layout);
        webPanel1Layout.setHorizontalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deviceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addComponent(webLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conditionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addComponent(webLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addComponent(webLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(668, Short.MAX_VALUE))
        );
        webPanel1Layout.setVerticalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conditionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", webPanel1);

        usageTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Used By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usageTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        usageTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(usageTbl);
        if (usageTbl.getColumnModel().getColumnCount() > 0) {
            usageTbl.getColumnModel().getColumn(1).setResizable(false);
            usageTbl.getColumnModel().getColumn(1).setHeaderValue("Reserved By");
        }

        addReportBtn.setForeground(new java.awt.Color(0, 0, 255));
        addReportBtn.setText("Add Maintenance Report");
        addReportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addComponent(addReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 653, Short.MAX_VALUE)))
                .addContainerGap())
        );
        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usage History", webPanel2);

        scheduleTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Reserved By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scheduleTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        scheduleTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(scheduleTbl);
        if (scheduleTbl.getColumnModel().getColumnCount() > 0) {
            scheduleTbl.getColumnModel().getColumn(1).setResizable(false);
            scheduleTbl.getColumnModel().getColumn(1).setHeaderValue("Reserved By");
        }

        javax.swing.GroupLayout webPanel3Layout = new javax.swing.GroupLayout(webPanel3);
        webPanel3.setLayout(webPanel3Layout);
        webPanel3Layout.setHorizontalGroup(
            webPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        webPanel3Layout.setVerticalGroup(
            webPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Future Schedule", webPanel3);

        webLabel24.setText("Product ID:");
        webLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        productNameLbl.setForeground(new java.awt.Color(0, 51, 255));
        productNameLbl.setText("Add Payment");
        productNameLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        webLabel25.setText("Product Cost:");
        webLabel25.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel26.setText("Product Description:");
        webLabel26.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        descriptionTxt.setEditable(false);
        descriptionTxt.setColumns(20);
        descriptionTxt.setRows(5);
        jScrollPane1.setViewportView(descriptionTxt);

        productIdLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        productCostLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout webPanel4Layout = new javax.swing.GroupLayout(webPanel4);
        webPanel4.setLayout(webPanel4Layout);
        webPanel4Layout.setHorizontalGroup(
            webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
            .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(webPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(webPanel4Layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addContainerGap())
                        .addGroup(webPanel4Layout.createSequentialGroup()
                            .addGap(0, 341, Short.MAX_VALUE)
                            .addComponent(productNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(426, 426, 426))
                        .addGroup(webPanel4Layout.createSequentialGroup()
                            .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(webPanel4Layout.createSequentialGroup()
                                    .addComponent(webLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(productCostLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(webPanel4Layout.createSequentialGroup()
                                    .addComponent(webLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(productIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(webLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        webPanel4Layout.setVerticalGroup(
            webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(webPanel4Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(productNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(webLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(webPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(webLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(productCostLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(67, 67, 67)
                    .addComponent(webLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Device Description", webPanel4);

        reportTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        reportTbl.getTableHeader().setReorderingAllowed(false);
        reportTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportTblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(reportTbl);

        webLabel15.setText("Maintenance Date:");
        webLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        maintenanceDateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel16.setText("Report Creation Date:");
        webLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        reportDateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel17.setText("Created By:");
        webLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        createdByLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel18.setText("Maintenance Cost:");
        webLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        costLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel19.setText("Report:");
        webLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        reportLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        webLabel20.setText("Report ID:");
        webLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        reportIdLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout webPanel5Layout = new javax.swing.GroupLayout(webPanel5);
        webPanel5.setLayout(webPanel5Layout);
        webPanel5Layout.setHorizontalGroup(
            webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(webPanel5Layout.createSequentialGroup()
                        .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(webPanel5Layout.createSequentialGroup()
                                .addComponent(webLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createdByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel5Layout.createSequentialGroup()
                                .addComponent(webLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reportIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel5Layout.createSequentialGroup()
                                .addComponent(webLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maintenanceDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel5Layout.createSequentialGroup()
                                .addComponent(webLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reportDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(webLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(webPanel5Layout.createSequentialGroup()
                                .addComponent(webLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        webPanel5Layout.setVerticalGroup(
            webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel5Layout.createSequentialGroup()
                .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maintenanceDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createdByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(webLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reportLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Maintenance History", webPanel5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReportBtnActionPerformed

        try {

            int selectedRow = usageTbl.getSelectedRow();

            if (selectedRow >= 0) {

                Schedule schedule = (Schedule) usageTbl.getValueAt(selectedRow,
                        0);

                if (schedule.getScheduleType()
                        .equals(Schedule.MAINTENANCE_SCHEDULE)) {
                    CreateMaintenanceReport createMaintenanceReport
                            = new CreateMaintenanceReport(MainFrame.mainFrame,
                                    true, inventoryItem, schedule, this);
                    createMaintenanceReport.setVisible(true);
                } else {
                    WebOptionPane.showMessageDialog(null,
                            "Please select a maintenance schedule", "Error",
                            WebOptionPane.ERROR_MESSAGE);
                }

            } else {
                WebOptionPane.showMessageDialog(null,
                        "Please select a maintenance schedule", "Error",
                        WebOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addReportBtnActionPerformed

    private void reportTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportTblMouseClicked

        try {

            int selectedRow = reportTbl.getSelectedRow();

            if (selectedRow >= 0) {

                MaintenanceReport maintenanceReport
                        = (MaintenanceReport) reportTbl.getValueAt(selectedRow,
                                0);

                reportIdLbl.setText(maintenanceReport.getReportID());
                maintenanceDateLbl.setText(CommonUtil
                        .changeDateFormat(maintenanceReport
                                .getMaintenanceDate(), "dd MMM, yyyy"));
                reportDateLbl.setText(CommonUtil
                        .changeDateFormat(maintenanceReport
                                .getReportCreationDate(), "dd MMM, yyyy"));
                createdByLbl.setText(inventoryManager.getFullName());
                costLbl.setText("$" + maintenanceReport.getCost());
                reportLbl.setText(maintenanceReport.getReport());

            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_reportTblMouseClicked

    /*  
     Populates reports in the table
    
     Paramters: NONE
    
     Returns: NONE
     */
    public void populateReports() {

        try {

            DefaultTableModel defaultTableModel
                    = (DefaultTableModel) reportTbl.getModel();
            defaultTableModel.setRowCount(0);

            Object row[];
            for (MaintenanceReport maintenanceReport : inventoryItem
                    .getMaintenanceHistory().getReportList()) {

                row = new Object[1];
                row[0] = maintenanceReport;
                defaultTableModel.addRow(row);

            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItemDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewItemDetails dialog
                        = new ViewItemDetails(new javax.swing.JFrame(), true,
                                inventoryItem, deviceStatus, inventoryManager);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton addReportBtn;
    private com.alee.laf.label.WebLabel addedOnLbl;
    private com.alee.laf.label.WebLabel conditionLbl;
    private com.alee.laf.label.WebLabel costLbl;
    private com.alee.laf.label.WebLabel createdByLbl;
    private com.alee.laf.label.WebLabel currentLocationLbl;
    private com.alee.laf.text.WebTextArea descriptionTxt;
    private com.alee.laf.label.WebLabel deviceLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.alee.laf.label.WebLabel maintenanceDateLbl;
    private com.alee.laf.label.WebLabel productCostLbl;
    private com.alee.laf.label.WebLabel productIdLbl;
    private com.alee.laf.label.WebLabel productNameLbl;
    private com.alee.laf.label.WebLabel reportDateLbl;
    private com.alee.laf.label.WebLabel reportIdLbl;
    private com.alee.extended.label.WebMultiLineLabel reportLbl;
    private com.alee.laf.table.WebTable reportTbl;
    private com.alee.laf.table.WebTable scheduleTbl;
    private com.alee.laf.label.WebLabel serialNoLbl;
    private com.alee.laf.table.WebTable usageTbl;
    private com.alee.laf.label.WebLabel webLabel10;
    private com.alee.laf.label.WebLabel webLabel11;
    private com.alee.laf.label.WebLabel webLabel12;
    private com.alee.laf.label.WebLabel webLabel13;
    private com.alee.laf.label.WebLabel webLabel14;
    private com.alee.laf.label.WebLabel webLabel15;
    private com.alee.laf.label.WebLabel webLabel16;
    private com.alee.laf.label.WebLabel webLabel17;
    private com.alee.laf.label.WebLabel webLabel18;
    private com.alee.laf.label.WebLabel webLabel19;
    private com.alee.laf.label.WebLabel webLabel20;
    private com.alee.laf.label.WebLabel webLabel24;
    private com.alee.laf.label.WebLabel webLabel25;
    private com.alee.laf.label.WebLabel webLabel26;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    private com.alee.laf.panel.WebPanel webPanel3;
    private com.alee.laf.panel.WebPanel webPanel4;
    private com.alee.laf.panel.WebPanel webPanel5;
    // End of variables declaration//GEN-END:variables
}
