/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.inventorymanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.request.OrderRequest;
import com.neu.phmis.business.sales.Cheque;
import com.neu.phmis.business.sales.ETransfer;
import com.neu.phmis.business.sales.Order;
import com.neu.phmis.business.sales.OrderItem;
import com.neu.phmis.business.sales.Payment;
import com.neu.phmis.business.util.CommonUtil;
import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ViewInventoryOrderDetailDialog extends javax.swing.JDialog {

    private Order order;
    private OrderRequest orderRequest;

    /**
     * Creates new form ViewSalesOrderDetail
     */
    public ViewInventoryOrderDetailDialog(java.awt.Frame parent, boolean modal,
            OrderRequest orderRequest) {

        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.orderRequest = orderRequest;
        order = orderRequest.getOrder();

        orderIdLbl.setText("Order No. " + order.getOrderId());
        orderedFromLbl.setText(order.getSupplierEnterprise()
                .getEnterpriseName());
        createdOnLbl.setText(CommonUtil.changeDateFormat(order.getCreatedOn(),
                "dd MMM, yyyy"));
        deliveryStatusLbl.setText(order.getIsDelivered() == 1
                ? OrderRequest.STATUS_DELIVERED : OrderRequest.STATUS_PENDING);
        totalCostLbl.setText("$ " + order.getTotalCost());

        DefaultTableModel defaultTableModel
                = (DefaultTableModel) productTbl.getModel();

        Object row[];
        for (OrderItem orderItem : order.getOrderItemList()) {

            row = new Object[3];
            row[0] = orderItem;
            row[1] = orderItem.getQuantity();
            row[2] = "$" + orderItem.getAmount();
            defaultTableModel.addRow(row);

        }

        if (order.getInvoice() == null) {
            invoicePanel.setEnabled(false);
        } else {
            populateTable();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab = new javax.swing.JTabbedPane();
        webPanel1 = new com.alee.laf.panel.WebPanel();
        webLabel10 = new com.alee.laf.label.WebLabel();
        webLabel15 = new com.alee.laf.label.WebLabel();
        totalCostLbl = new com.alee.laf.label.WebLabel();
        orderedFromLbl = new com.alee.laf.label.WebLabel();
        deliveryStatusLbl = new com.alee.laf.label.WebLabel();
        webLabel13 = new com.alee.laf.label.WebLabel();
        webLabel11 = new com.alee.laf.label.WebLabel();
        createdOnLbl = new com.alee.laf.label.WebLabel();
        webLabel12 = new com.alee.laf.label.WebLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTbl = new com.alee.laf.table.WebTable();
        orderIdLbl = new com.alee.laf.label.WebLabel();
        invoicePanel = new com.alee.laf.panel.WebPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderItemsTbl = new com.alee.laf.table.WebTable();
        orderIdLbl1 = new com.alee.laf.label.WebLabel();
        webLabel14 = new com.alee.laf.label.WebLabel();
        invoiceNumberLbl = new com.alee.laf.label.WebLabel();
        dateLbl = new com.alee.laf.label.WebLabel();
        webLabel16 = new com.alee.laf.label.WebLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        paymentTbl = new com.alee.laf.table.WebTable();
        webLabel17 = new com.alee.laf.label.WebLabel();
        grandTotalLbl = new com.alee.laf.label.WebLabel();
        webLabel18 = new com.alee.laf.label.WebLabel();
        webLabel19 = new com.alee.laf.label.WebLabel();
        amountPaidLbl = new com.alee.laf.label.WebLabel();
        webLabel20 = new com.alee.laf.label.WebLabel();
        amountDueLbl = new com.alee.laf.label.WebLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tab.setForeground(new java.awt.Color(51, 51, 255));
        Tab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        webLabel10.setText("Ordered From:");
        webLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel15.setText("Order Items:");
        webLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        totalCostLbl.setText("<No of Staff>");
        totalCostLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        orderedFromLbl.setText("<No of Staff>");
        orderedFromLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        deliveryStatusLbl.setText("<No of Staff>");
        deliveryStatusLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel13.setText("Total Cost:");
        webLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel11.setText("Created On:");
        webLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        createdOnLbl.setText("<No of Staff>");
        createdOnLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel12.setText("Delivery Status:");
        webLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        productTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(productTbl);

        orderIdLbl.setForeground(new java.awt.Color(0, 51, 255));
        orderIdLbl.setText("<Label>");
        orderIdLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout webPanel1Layout = new javax.swing.GroupLayout(webPanel1);
        webPanel1.setLayout(webPanel1Layout);
        webPanel1Layout.setHorizontalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(webPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, webPanel1Layout.createSequentialGroup()
                                .addComponent(webLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalCostLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createdOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addComponent(webLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deliveryStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(webPanel1Layout.createSequentialGroup()
                                    .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(orderIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(orderedFromLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        webPanel1Layout.setVerticalGroup(
            webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderedFromLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createdOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCostLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(webLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        Tab.addTab("Order Details", webPanel1);

        orderItemsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Particulars", "Quantity", "Cost", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderItemsTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(orderItemsTbl);

        orderIdLbl1.setForeground(new java.awt.Color(0, 51, 255));
        orderIdLbl1.setText("Invoice");
        orderIdLbl1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        webLabel14.setText("Invoice Number:");
        webLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        invoiceNumberLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        dateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel16.setText("Date:");
        webLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        paymentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment Date", "Payment Mode", "Cheque No./Transaction ID", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(paymentTbl);

        webLabel17.setText("Grand Total:");
        webLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        grandTotalLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel18.setText("Payment History:");
        webLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel19.setText("Amount Paid:");
        webLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        amountPaidLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel20.setText("Amount Due:");
        webLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        amountDueLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addComponent(webLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(webLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(orderIdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoicePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(webLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grandTotalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addComponent(webLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoicePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(webLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountPaidLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoicePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(webLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountDueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        invoicePanelLayout.setVerticalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderIdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grandTotalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(webLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountPaidLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountDueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Tab.addTab("Invoice", invoicePanel);

        getContentPane().add(Tab, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* ---------------------------------------------------------------------- */
    /*
     Populates the table with product details
    
     Parameters: NONE
    
     Returns: NONE
     */
    public void populateTable() {

        try {

            invoiceNumberLbl.setText(order.getInvoice().getInvoiceNumber());
            dateLbl.setText(CommonUtil.changeDateFormat(order.getInvoice()
                    .getCreatedOn(), "dd MMM, yyyy"));

            DefaultTableModel defaultTableModel
                    = (DefaultTableModel) orderItemsTbl.getModel();

            Object row[];
            for (OrderItem orderItem : order.getOrderItemList()) {

                row = new Object[4];
                row[0] = orderItem;
                row[1] = orderItem.getQuantity();
                row[2] = "$" + orderItem.getProduct().getProductCost();
                row[3] = "$" + orderItem.getAmount();
                defaultTableModel.addRow(row);

            }

            defaultTableModel = (DefaultTableModel) paymentTbl.getModel();
            for (Payment payment : order.getInvoice().getPaymentHistory()
                    .getPaymentList()) {

                String info = "";
                if (payment.getPaymentType().equals(Payment.CHEQUE)) {
                    info = ((Cheque) payment).getChequeNumber();
                } else if (payment.getPaymentType().equals(Payment.ETRANSFER)) {
                    info = ((ETransfer) payment).getTransactionId();
                }

                row = new Object[4];
                row[0] = payment;
                row[1] = payment.getPaymentType();
                row[2] = info;
                row[3] = "$" + payment.getAmount();
                defaultTableModel.addRow(row);

            }

            BigDecimal total = order.getTotalCost();
            BigDecimal paid = order.getInvoice().getPaymentHistory()
                    .getTotalPayment();
            BigDecimal due = BigDecimal.valueOf(total.doubleValue() - paid
                    .doubleValue());

            grandTotalLbl.setText("$" + total);
            amountPaidLbl.setText("$" + paid);
            amountDueLbl.setText("$" + due);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInventoryOrderDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInventoryOrderDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInventoryOrderDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInventoryOrderDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewInventoryOrderDetailDialog dialog
                        = new ViewInventoryOrderDetailDialog(
                                new javax.swing.JFrame(), true, orderRequest);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tab;
    private com.alee.laf.label.WebLabel amountDueLbl;
    private com.alee.laf.label.WebLabel amountPaidLbl;
    private com.alee.laf.label.WebLabel createdOnLbl;
    private com.alee.laf.label.WebLabel dateLbl;
    private com.alee.laf.label.WebLabel deliveryStatusLbl;
    private com.alee.laf.label.WebLabel grandTotalLbl;
    private com.alee.laf.label.WebLabel invoiceNumberLbl;
    private com.alee.laf.panel.WebPanel invoicePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.alee.laf.label.WebLabel orderIdLbl;
    private com.alee.laf.label.WebLabel orderIdLbl1;
    private com.alee.laf.table.WebTable orderItemsTbl;
    private com.alee.laf.label.WebLabel orderedFromLbl;
    private com.alee.laf.table.WebTable paymentTbl;
    private com.alee.laf.table.WebTable productTbl;
    private com.alee.laf.label.WebLabel totalCostLbl;
    private com.alee.laf.label.WebLabel webLabel10;
    private com.alee.laf.label.WebLabel webLabel11;
    private com.alee.laf.label.WebLabel webLabel12;
    private com.alee.laf.label.WebLabel webLabel13;
    private com.alee.laf.label.WebLabel webLabel14;
    private com.alee.laf.label.WebLabel webLabel15;
    private com.alee.laf.label.WebLabel webLabel16;
    private com.alee.laf.label.WebLabel webLabel17;
    private com.alee.laf.label.WebLabel webLabel18;
    private com.alee.laf.label.WebLabel webLabel19;
    private com.alee.laf.label.WebLabel webLabel20;
    private com.alee.laf.panel.WebPanel webPanel1;
    // End of variables declaration//GEN-END:variables
}
