/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.inventorymanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.enterprise.WarehouseEnterprise;
import com.neu.phmis.business.request.DeviceRequest;
import com.neu.phmis.business.user.InventoryManager;
import com.neu.phmis.business.user.Person;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.business.util.MailUtil;
import com.neu.phmis.userinterface.MainFrame;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ViewDeviceRequestPanel extends javax.swing.JPanel {

    private DeviceRequest deviceRequest;
    private InventoryManager inventoryManager;
    private WarehouseEnterprise warehouseEnterprise;
    private JPanel container;

    /**
     * Creates new form ViewDeviceRequestPanel
     */
    public ViewDeviceRequestPanel(DeviceRequest deviceRequest,
            InventoryManager inventoryManager,
            WarehouseEnterprise warehouseEnterprise, JPanel container) {

        initComponents();

        this.deviceRequest = deviceRequest;
        this.inventoryManager = inventoryManager;
        this.warehouseEnterprise = warehouseEnterprise;
        this.container = container;

        requestIdLbl.setText(deviceRequest.getRequestId());
        senderLbl.setText(deviceRequest.getHospitalEnterprise()
                .getEnterpriseName());
        personLbl.setText(deviceRequest.getSentBy().getFullName());
        createdOnLbl.setText(CommonUtil.changeDateFormat(deviceRequest
                .getCreatedOn(), "dd MMM, yyyy"));

        if (deviceRequest.getSpecialInstruction().isEmpty()) {
            splInstrTitleLbl.setVisible(false);
            specialInstructionsLbl.setVisible(false);
        } else {
            specialInstructionsLbl.setText(deviceRequest
                    .getSpecialInstruction());
        }

        statusLbl.setText(deviceRequest.getStatus());
        if (deviceRequest.getStatus().equals(DeviceRequest.STATUS_PENDING)) {
            processedByLbl.setVisible(false);
            processedByTitleLbl.setVisible(false);
            processedOnLbl.setVisible(false);
            processedOnTitleLbl.setVisible(false);
        } else {
            processedByLbl.setText(deviceRequest.getProcessedBy()
                    .getFullName());
            processedOnLbl.setText(CommonUtil.changeDateFormat(deviceRequest
                    .getProcessedOn(), "dd MMM, yyyy"));
        }

        DefaultTableModel defaultTableModel = (DefaultTableModel) productsTable
                .getModel();
        defaultTableModel.setRowCount(0);

        Object rows[] = null;
        for (String products : deviceRequest.getDeviceList()) {
            rows = new Object[1];
            rows[0] = products;
            defaultTableModel.addRow(rows);
        }

        if (deviceRequest.getStatus().equals(DeviceRequest.STATUS_AVAILABLE)
                || deviceRequest.getStatus()
                .equals(DeviceRequest.STATUS_DISAPPROVED)) {
            processRequestBtn.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webPanel1 = new com.alee.laf.panel.WebPanel();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        webLabel1 = new com.alee.laf.label.WebLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        requestIdLbl = new com.alee.laf.label.WebLabel();
        webLabel6 = new com.alee.laf.label.WebLabel();
        personLbl = new com.alee.laf.label.WebLabel();
        webLabel7 = new com.alee.laf.label.WebLabel();
        createdOnLbl = new com.alee.laf.label.WebLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productsTable = new com.alee.laf.table.WebTable();
        splInstrTitleLbl = new com.alee.laf.label.WebLabel();
        specialInstructionsLbl = new com.alee.extended.label.WebMultiLineLabel();
        processRequestBtn = new com.alee.laf.button.WebButton();
        backBtn = new com.alee.laf.button.WebButton();
        processedByTitleLbl = new com.alee.laf.label.WebLabel();
        processedOnTitleLbl = new com.alee.laf.label.WebLabel();
        processedByLbl = new com.alee.laf.label.WebLabel();
        processedOnLbl = new com.alee.laf.label.WebLabel();
        statusTitleLbl = new com.alee.laf.label.WebLabel();
        statusLbl = new com.alee.laf.label.WebLabel();
        webLabel8 = new com.alee.laf.label.WebLabel();
        senderLbl = new com.alee.laf.label.WebLabel();

        setLayout(new java.awt.BorderLayout());

        webLabel1.setForeground(new java.awt.Color(0, 51, 255));
        webLabel1.setText("New Device Request");
        webLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        webLabel5.setText("Request ID:");
        webLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        requestIdLbl.setText("<Request ID>");
        requestIdLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel6.setText("Person:");
        webLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        personLbl.setText("<Person Name>");
        personLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel7.setText("Created On:");
        webLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        createdOnLbl.setText("<Creation Date>");
        createdOnLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device List"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productsTable);

        splInstrTitleLbl.setText("Special Instructions:");
        splInstrTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        specialInstructionsLbl.setText("<Instructions>");
        specialInstructionsLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        processRequestBtn.setForeground(new java.awt.Color(0, 0, 255));
        processRequestBtn.setText("Process");
        processRequestBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        processRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestBtnActionPerformed(evt);
            }
        });

        backBtn.setForeground(new java.awt.Color(0, 0, 255));
        backBtn.setText("Back");
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        processedByTitleLbl.setText("Processed By:");
        processedByTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnTitleLbl.setText("Processed On:");
        processedOnTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByLbl.setText("<Processed By>");
        processedByLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnLbl.setText("<Processed On>");
        processedOnLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        statusTitleLbl.setText("Status:");
        statusTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        statusLbl.setText("<Status>");
        statusLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel8.setText("Sender:");
        webLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        senderLbl.setText("<Sender Name>");
        senderLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(splInstrTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(webPanel2Layout.createSequentialGroup()
                                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(webPanel2Layout.createSequentialGroup()
                                            .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(createdOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(webPanel2Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(webPanel2Layout.createSequentialGroup()
                                                    .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(requestIdLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(personLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                                                .addGroup(webPanel2Layout.createSequentialGroup()
                                                    .addGap(28, 28, 28)
                                                    .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(senderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(webPanel2Layout.createSequentialGroup()
                                        .addComponent(statusTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(webPanel2Layout.createSequentialGroup()
                                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel2Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(processRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(webPanel2Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addComponent(specialInstructionsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(272, 272, 272))))
        );
        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createdOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(splInstrTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialInstructionsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        add(webPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        try {
            ManageInventoryRequestsPanel manageInventoryRequestsPanel
                    = new ManageInventoryRequestsPanel(warehouseEnterprise,
                            inventoryManager, container);
            CommonUtil.insertNewPanel(container, "Manage Inventory",
                    manageInventoryRequestsPanel, null);
        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_backBtnActionPerformed

    private void processRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestBtnActionPerformed

        try {

            if (!deviceRequest.getStatus()
                    .equals(DeviceRequest.STATUS_APPROVED)) {

                ProcessRequestDialog processRequestDialog
                        = new ProcessRequestDialog(MainFrame.mainFrame, true,
                                deviceRequest, inventoryManager, container,
                                warehouseEnterprise, this);
                processRequestDialog.setVisible(true);

            } else {

                String message = "Please click YES if you want to mark this "
                        + "request as available and NO if you want to mark it "
                        + "cancelled.";

                int ans = WebOptionPane.showConfirmDialog(null, message,
                        "Please Confirm", WebOptionPane.YES_NO_CANCEL_OPTION);

                if (ans == WebOptionPane.YES_OPTION) {

                    deviceRequest.setStatus(DeviceRequest.STATUS_AVAILABLE);
                    deviceRequest.setProcessedBy(inventoryManager);
                    deviceRequest.setProcessedOn(new Date());
                    backBtnActionPerformed(evt);

                    CommonUtil.saveChanges(Ecosystem.getInstance());
                    
                    Person person = deviceRequest.getSentBy();
                    MailUtil mailUtil = new MailUtil(person.getEmailId());
                    StringBuffer stringBuffer = new StringBuffer();
                    stringBuffer.append(person).append(",\nThe following "
                            + "devices which you had requested are now "
                            + "available in the inventory:\n");
                    int count = 0;
                    for (String device : deviceRequest.getDeviceList()) {
                        stringBuffer.append(++count).append(". ").append(device)
                                .append("\n");
                    }
                    mailUtil.setEmailBody(stringBuffer.toString());
                    mailUtil.setEmailSubject("Device Request Status Update");
                    mailUtil.sendEmail();

                } else if (ans == WebOptionPane.NO_OPTION) {

                    deviceRequest.setStatus(DeviceRequest.STATUS_CANCELLED);
                    deviceRequest.setProcessedBy(inventoryManager);
                    deviceRequest.setProcessedOn(new Date());
                    backBtnActionPerformed(evt);
                    
                    CommonUtil.saveChanges(Ecosystem.getInstance());

                    Person person = deviceRequest.getSentBy();
                    MailUtil mailUtil = new MailUtil(person.getEmailId());
                    StringBuffer stringBuffer = new StringBuffer();
                    stringBuffer.append(person).append(",\nUnfortunately, your "
                            + "requested devices could not added to the "
                            + "inventory. The order for the devices got "
                            + "cancelled from the vendor side.");
                    mailUtil.setEmailBody(stringBuffer.toString());
                    mailUtil.setEmailSubject("Device Request Status Update");
                    mailUtil.sendEmail();

                }

            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_processRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton backBtn;
    private com.alee.laf.label.WebLabel createdOnLbl;
    private javax.swing.JScrollPane jScrollPane2;
    private com.alee.laf.label.WebLabel personLbl;
    private com.alee.laf.button.WebButton processRequestBtn;
    private com.alee.laf.label.WebLabel processedByLbl;
    private com.alee.laf.label.WebLabel processedByTitleLbl;
    private com.alee.laf.label.WebLabel processedOnLbl;
    private com.alee.laf.label.WebLabel processedOnTitleLbl;
    private com.alee.laf.table.WebTable productsTable;
    private com.alee.laf.label.WebLabel requestIdLbl;
    private com.alee.laf.label.WebLabel senderLbl;
    private com.alee.extended.label.WebMultiLineLabel specialInstructionsLbl;
    private com.alee.laf.label.WebLabel splInstrTitleLbl;
    private com.alee.laf.label.WebLabel statusLbl;
    private com.alee.laf.label.WebLabel statusTitleLbl;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel6;
    private com.alee.laf.label.WebLabel webLabel7;
    private com.alee.laf.label.WebLabel webLabel8;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    // End of variables declaration//GEN-END:variables
}
