/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.productmanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.organization.ProductOrganization;
import com.neu.phmis.business.user.ProductManager;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.userinterface.LoginPanel;
import com.neu.phmis.userinterface.MainFrame;

/**
 *
 * @author Vineet
 */
public class ProductManagerDashboardPanel extends javax.swing.JPanel {

    private Ecosystem ecosystem;
    private ProductOrganization productOrganization;
    private ProductManager productManager;

    /**
     * Creates new form ProductManagerDashboardPanel
     */
    public ProductManagerDashboardPanel(ProductManager productManager) {

        initComponents();

        ecosystem = Ecosystem.getInstance();
        productOrganization = (ProductOrganization) productManager
                .getOrganization();
        this.productManager = productManager;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webPanel1 = new com.alee.laf.panel.WebPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        myAccountBtn = new com.alee.laf.button.WebButton();
        logoutBtn = new com.alee.laf.button.WebButton();
        ordersBtn = new com.alee.laf.button.WebButton();
        productOrgContainer = new com.alee.laf.panel.WebPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        myAccountBtn.setForeground(new java.awt.Color(0, 0, 255));
        myAccountBtn.setText("Products");
        myAccountBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccountBtnActionPerformed(evt);
            }
        });

        logoutBtn.setForeground(new java.awt.Color(0, 0, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        ordersBtn.setForeground(new java.awt.Color(0, 0, 255));
        ordersBtn.setText("Orders");
        ordersBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ordersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myAccountBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ordersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(webPanel2);

        productOrgContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(productOrgContainer);

        webPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(webPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void myAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccountBtnActionPerformed

        try {

            ManageProductsPanel manageProductsPanel
                    = new ManageProductsPanel(productOrganization);
            CommonUtil.insertNewPanel(productOrgContainer,
                    "Manage Product Panel", manageProductsPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured", "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_myAccountBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed

        try {
            CommonUtil.saveChanges(ecosystem);
            LoginPanel loginPanel
                    = new LoginPanel(MainFrame.mainFrame.getContainer(),
                            ecosystem);
            CommonUtil.insertNewPanel(MainFrame.mainFrame.getContainer(),
                    "Login Panel", loginPanel, this);
        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void ordersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBtnActionPerformed

        try {

            ManageOrdersPanel manageOrdersPanel
                    = new ManageOrdersPanel(productManager);
            CommonUtil.insertNewPanel(productOrgContainer, "Manage Order Panel",
                    manageOrdersPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ordersBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private com.alee.laf.button.WebButton logoutBtn;
    private com.alee.laf.button.WebButton myAccountBtn;
    private com.alee.laf.button.WebButton ordersBtn;
    private com.alee.laf.panel.WebPanel productOrgContainer;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    // End of variables declaration//GEN-END:variables
}
