/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.productmanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.enterprise.SupplierEnterprise;
import com.neu.phmis.business.request.OrderRequest;
import com.neu.phmis.business.sales.OrderItem;
import com.neu.phmis.business.user.Person;
import com.neu.phmis.business.user.ProductManager;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.business.util.MailUtil;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ViewOrderDialog extends javax.swing.JDialog {

    private OrderRequest orderRequest;
    private ProductManager productManager;
    private ManageOrdersPanel manageOrdersPanel;
    private Ecosystem ecosystem;

    /**
     * Creates new form ViewOrderDialog
     */
    public ViewOrderDialog(java.awt.Frame parent, boolean modal,
            OrderRequest orderRequest, ProductManager productManager,
            ManageOrdersPanel manageOrdersPanel) {

        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        this.orderRequest = orderRequest;
        this.productManager = productManager;
        this.manageOrdersPanel = manageOrdersPanel;
        ecosystem = Ecosystem.getInstance();

        requestIdLbl.setText(orderRequest.getRequestId());
        warehouseLbl.setText(orderRequest.getWarehouseEnterprise()
                .getEnterpriseName());
        personLbl.setText(orderRequest.getSentBy().getFullName());
        creationDateLbl.setText(CommonUtil.changeDateFormat(orderRequest
                .getCreatedOn(), "dd MMM. yyyy"));
        statusLbl.setText(orderRequest.getStatus());
        if (!orderRequest.getStatus().equals(OrderRequest.STATUS_PENDING)) {
            processedByLbl.setText(orderRequest.getProcessedBy().getFullName());
            processedOnLbl.setText(CommonUtil.changeDateFormat(orderRequest
                    .getProcessedOn(), "dd MMM, yyyy"));
            processBtn.setEnabled(false);
        } else {
            processedByLbl.setVisible(false);
            processedOnLbl.setVisible(false);
            processedByTitleLbl.setVisible(false);
            processedOnTitleLbl.setVisible(false);
        }

        DefaultTableModel defaultTableModel = (DefaultTableModel) productListTbl
                .getModel();

        Object row[] = null;
        for (OrderItem orderItem : orderRequest.getOrder().getOrderItemList()) {

            row = new Object[2];
            row[0] = orderItem;
            row[1] = orderItem.getQuantity();

            defaultTableModel.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webLabel1 = new com.alee.laf.label.WebLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        requestIdLbl = new com.alee.laf.label.WebLabel();
        webLabel6 = new com.alee.laf.label.WebLabel();
        warehouseLbl = new com.alee.laf.label.WebLabel();
        webLabel7 = new com.alee.laf.label.WebLabel();
        personLbl = new com.alee.laf.label.WebLabel();
        webLabel8 = new com.alee.laf.label.WebLabel();
        creationDateLbl = new com.alee.laf.label.WebLabel();
        statusLbl = new com.alee.laf.label.WebLabel();
        webLabel9 = new com.alee.laf.label.WebLabel();
        processedByLbl = new com.alee.laf.label.WebLabel();
        processedByTitleLbl = new com.alee.laf.label.WebLabel();
        processedOnLbl = new com.alee.laf.label.WebLabel();
        processedOnTitleLbl = new com.alee.laf.label.WebLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productListTbl = new com.alee.laf.table.WebTable();
        processBtn = new com.alee.laf.button.WebButton();
        cancelBtn = new com.alee.laf.button.WebButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        webLabel1.setForeground(new java.awt.Color(0, 51, 255));
        webLabel1.setText("Order Request");
        webLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        webLabel5.setText("Request ID:");
        webLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        requestIdLbl.setText("<Request ID>");
        requestIdLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel6.setText("Requested By:");
        webLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        warehouseLbl.setText("<Requested by>");
        warehouseLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel7.setText("Person:");
        webLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        personLbl.setText("<Inventory Manager>");
        personLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel8.setText("Created On:");
        webLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        creationDateLbl.setText("<Creation Date>");
        creationDateLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        statusLbl.setText("<Status>");
        statusLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel9.setText("Status:");
        webLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByLbl.setText("<Processed By>");
        processedByLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedByTitleLbl.setText("Processed By:");
        processedByTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnLbl.setText("<Processed On>");
        processedOnLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        processedOnTitleLbl.setText("Processed On:");
        processedOnTitleLbl.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        productListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productListTbl);

        processBtn.setForeground(new java.awt.Color(0, 0, 255));
        processBtn.setText("Process");
        processBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        cancelBtn.setForeground(new java.awt.Color(0, 0, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(creationDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(personLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(warehouseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(requestIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warehouseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creationDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(webLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processedByTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processedOnTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(processedOnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed

        try {

            String message = "You can either approve or decline the order. "
                    + "Please click YES if you want to approve the order, NO "
                    + "if you want to decline it and CANCEL if you do not want "
                    + "to take any action";

            int ans = WebOptionPane.showConfirmDialog(null, message,
                    "Please Choose", WebOptionPane.YES_NO_CANCEL_OPTION);

            if (ans == WebOptionPane.YES_OPTION) {

                orderRequest.setStatus(OrderRequest.STATUS_CONFIRMED);
                orderRequest.setProcessedBy(productManager);
                orderRequest.setProcessedOn(new Date());

                SupplierEnterprise supplierEnterprise
                        = (SupplierEnterprise) productManager.getEnterprise();
                supplierEnterprise.getOrderDirectory().getOrderList()
                        .add(orderRequest.getOrder());

                orderRequest.getOrder().generateInvoice();
                orderRequest.getOrder().setCreatedOn(new Date());
                this.dispose();
                CommonUtil.saveChanges(ecosystem);

                Person person = orderRequest.getSentBy();
                MailUtil mailUtil = new MailUtil(person.getEmailId());
                StringBuffer stringBuffer = new StringBuffer();
                stringBuffer.append(person).append(",\n Your order request "
                        + "with Request ID ").append(orderRequest)
                        .append(" has been approved. Your order ID is as "
                                + "follows:\n").append(orderRequest.getOrder());
                mailUtil.setEmailBody(stringBuffer.toString());
                mailUtil.setEmailSubject("Order Request Status Update");
                mailUtil.sendEmail();

            } else if (ans == WebOptionPane.NO_OPTION) {

                orderRequest.setStatus(OrderRequest.STATUS_CANCELLED);
                orderRequest.setProcessedBy(productManager);
                orderRequest.setProcessedOn(new Date());
                this.dispose();
                CommonUtil.saveChanges(ecosystem);

                Person person = orderRequest.getSentBy();
                MailUtil mailUtil = new MailUtil(person.getEmailId());
                StringBuffer stringBuffer = new StringBuffer();
                stringBuffer.append(person).append(",\n Your order request "
                        + "with Request ID ").append(orderRequest)
                        .append(" has been declined. For more details, please "
                                + "contact ").append(productManager
                                .getEnterprise());
                mailUtil.setEmailBody(stringBuffer.toString());
                mailUtil.setEmailSubject("Order Request Status Update");
                mailUtil.sendEmail();

            }

            manageOrdersPanel.populateTable();

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_processBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewOrderDialog dialog
                        = new ViewOrderDialog(new javax.swing.JFrame(), true,
                                orderRequest, productManager,
                                manageOrdersPanel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton cancelBtn;
    private com.alee.laf.label.WebLabel creationDateLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private com.alee.laf.label.WebLabel personLbl;
    private com.alee.laf.button.WebButton processBtn;
    private com.alee.laf.label.WebLabel processedByLbl;
    private com.alee.laf.label.WebLabel processedByTitleLbl;
    private com.alee.laf.label.WebLabel processedOnLbl;
    private com.alee.laf.label.WebLabel processedOnTitleLbl;
    private com.alee.laf.table.WebTable productListTbl;
    private com.alee.laf.label.WebLabel requestIdLbl;
    private com.alee.laf.label.WebLabel statusLbl;
    private com.alee.laf.label.WebLabel warehouseLbl;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel6;
    private com.alee.laf.label.WebLabel webLabel7;
    private com.alee.laf.label.WebLabel webLabel8;
    private com.alee.laf.label.WebLabel webLabel9;
    // End of variables declaration//GEN-END:variables
}
