/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.salesmanager;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.enterprise.SupplierEnterprise;
import com.neu.phmis.business.request.OrderRequest;
import com.neu.phmis.business.sales.Order;
import com.neu.phmis.business.user.SalesManager;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.userinterface.MainFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vineet
 */
public class ManageSalesOrdersPanel extends javax.swing.JPanel {

    private Ecosystem ecosystem;
    private SupplierEnterprise supplierEnterprise;
    private SalesManager salesManager;

    /**
     * Creates new form ManageOrdersPanel
     */
    public ManageSalesOrdersPanel(SalesManager salesManager) {

        initComponents();

        ecosystem = Ecosystem.getInstance();
        this.salesManager = salesManager;
        supplierEnterprise = (SupplierEnterprise) salesManager.getEnterprise();

        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTbl = new com.alee.laf.table.WebTable();
        viewOrderBtn = new com.alee.laf.button.WebButton();

        ordersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Warehouse", "Created On", "Delivery Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordersTbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(ordersTbl);

        viewOrderBtn.setForeground(new java.awt.Color(0, 0, 255));
        viewOrderBtn.setText("View");
        viewOrderBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(viewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBtnActionPerformed

        try {

            int selectedRow = ordersTbl.getSelectedRow();

            if (selectedRow >= 0) {

                ViewSalesOrderDetailDialog viewSalesOrderDetailDialog
                        = new ViewSalesOrderDetailDialog(MainFrame.mainFrame,
                                true, (Order) ordersTbl.getValueAt(selectedRow,
                                        0));
                viewSalesOrderDetailDialog.setVisible(true);
            } else {
                WebOptionPane.showMessageDialog(null, "No order selected",
                        "Error", WebOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_viewOrderBtnActionPerformed

    /* ---------------------------------------------------------------------- */
    /*
     Populates the table with order details
    
     Parameters: NONE
    
     Returns: NONE
     */
    public void populateTable() {

        try {

            DefaultTableModel defaultTableModel
                    = (DefaultTableModel) ordersTbl.getModel();
            defaultTableModel.setRowCount(0);

            Object row[];
            for (Order order : supplierEnterprise.getOrderDirectory()
                    .getOrderList()) {

                row = new Object[4];
                row[0] = order;
                row[1] = order.getWarehouseEnterprise();
                row[2] = CommonUtil.changeDateFormat(order.getCreatedOn(),
                        "dd MMM, yyyy");
                row[3] = order.getIsDelivered() == 0
                        ? OrderRequest.STATUS_PENDING
                        : OrderRequest.STATUS_DELIVERED;
                defaultTableModel.addRow(row);

            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.alee.laf.table.WebTable ordersTbl;
    private com.alee.laf.button.WebButton viewOrderBtn;
    // End of variables declaration//GEN-END:variables
}
