/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.systemadmin;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.enterprise.Enterprise;
import com.neu.phmis.business.network.Network;
import com.neu.phmis.business.user.Person;
import com.neu.phmis.business.user.UserAccount;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.business.util.Constants;
import com.neu.phmis.business.util.EncryptionUtil;
import com.neu.phmis.business.util.MailUtil;

/**
 *
 * @author Vineet
 */
public class CreateEnterpriseDialog extends javax.swing.JDialog {

    private Ecosystem ecosystem;
    private ManageEnterprisePanel manageEnterprisePanel;

    /**
     * Creates new form CreateEnterpriseDialog
     */
    public CreateEnterpriseDialog(java.awt.Frame parent, boolean modal,
            Ecosystem ecosystem, ManageEnterprisePanel manageEnterprisePanel) {

        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.ecosystem = ecosystem;
        this.manageEnterprisePanel = manageEnterprisePanel;

        for (Network network : ecosystem.getNetworkDirectory()
                .getNetworkList()) {
            networkCombo.addItem(network);
        }

        enterpriseTypeCombo.addItem(Enterprise.ENTERPRISE_HOSPITAL);
        enterpriseTypeCombo.addItem(Enterprise.ENTERPRISE_WAREHOUSE);
        enterpriseTypeCombo.addItem(Enterprise.ENTERPRISE_SUPPLIER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webPanel1 = new com.alee.laf.panel.WebPanel();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        webLabel1 = new com.alee.laf.label.WebLabel();
        webLabel2 = new com.alee.laf.label.WebLabel();
        networkCombo = new com.alee.laf.combobox.WebComboBox();
        webLabel3 = new com.alee.laf.label.WebLabel();
        enterpriseNameText = new com.alee.laf.text.WebTextField();
        webLabel4 = new com.alee.laf.label.WebLabel();
        enterpriseTypeCombo = new com.alee.laf.combobox.WebComboBox();
        webMultiLineLabel1 = new com.alee.extended.label.WebMultiLineLabel();
        webLabel5 = new com.alee.laf.label.WebLabel();
        firstNameText = new com.alee.laf.text.WebTextField();
        webLabel6 = new com.alee.laf.label.WebLabel();
        lastNameText = new com.alee.laf.text.WebTextField();
        webLabel7 = new com.alee.laf.label.WebLabel();
        emailText = new com.alee.laf.text.WebTextField();
        webLabel8 = new com.alee.laf.label.WebLabel();
        userNameText = new com.alee.laf.text.WebTextField();
        createPersonBtn = new com.alee.laf.button.WebButton();
        cancelBtn = new com.alee.laf.button.WebButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        webLabel1.setForeground(new java.awt.Color(0, 51, 255));
        webLabel1.setText("Create Enterprise");
        webLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        webLabel2.setText("Network:");
        webLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel3.setText("Enterprise Name:");
        webLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel4.setText("Enterprise Type:");
        webLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webMultiLineLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        webMultiLineLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webMultiLineLabel1.setText("Please enter details for creating the administrator account for the enterprise you are creating");

        webLabel5.setText("First Name:");
        webLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel6.setText("Last Name:");
        webLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel7.setText("Email ID:");
        webLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        webLabel8.setText("Username:");
        webLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });

        createPersonBtn.setForeground(new java.awt.Color(0, 0, 255));
        createPersonBtn.setText("Create");
        createPersonBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonBtnActionPerformed(evt);
            }
        });

        cancelBtn.setForeground(new java.awt.Color(0, 0, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(webLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(enterpriseNameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enterpriseTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(networkCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(webLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(userNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(webMultiLineLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(createPersonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(webLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(networkCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(enterpriseTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(webPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(webLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(webMultiLineLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(webLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(webLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPersonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        getContentPane().add(webPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextActionPerformed

    private void createPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonBtnActionPerformed

        try {
            String errors = validateForm();

            if (errors.isEmpty()) {

                Network network = (Network) networkCombo.getSelectedItem();
                String enterpriseType = (String) enterpriseTypeCombo
                        .getSelectedItem();

                Enterprise enterprise = null;
                if (enterpriseType.equals(Enterprise.ENTERPRISE_HOSPITAL)) {
                    enterprise = network.getHospitalEnterpriseDirectory()
                            .createEnterprise(enterpriseType);
                } else if (enterpriseType
                        .equals(Enterprise.ENTERPRISE_WAREHOUSE)) {
                    enterprise = network.getWarehouseEnterpriseDirectory()
                            .createEnterprise(enterpriseType);
                } else if (enterpriseType
                        .equals(Enterprise.ENTERPRISE_SUPPLIER)) {
                    enterprise = network.getSupplierEnterpriseDirectory()
                            .createEnterprise(enterpriseType);
                }

                enterprise.setEnterpriseName(enterpriseNameText.getText()
                        .trim());
                enterprise.setSupportedOrganizations();

                Person person = enterprise.getPersonDirectory().addPerson();
                person.setFirstName(firstNameText.getText().trim());
                person.setLastName(lastNameText.getText().trim());
                person.setEmailId(emailText.getText().trim());
                person.setOrganization(null);
                person.setEnterprise(enterprise);
                
                UserAccount userAccount = person.getUserAccount();
                userAccount.setUserName(userNameText.getText().trim());
                userAccount.setPassword(EncryptionUtil
                        .encrypt(userNameText.getText().trim()));
                userAccount.setRole(enterprise.getSupportedRoles());

                ecosystem.getMasterPersonDirectory().getPersonList()
                        .add(person);
                manageEnterprisePanel.populateTable();
                this.setVisible(false);

                MailUtil mailUtil = new MailUtil(person.getEmailId());
                StringBuffer stringBuffer = new StringBuffer();
                stringBuffer.append(enterprise).append(" has been successfully "
                        + "registered in the PHMIS. The access credentials for "
                        + "accessing your enterprise account are as "
                        + "follows:\n").append("Username - ").append(userAccount
                                .getUserName()).append("\nPassword - ")
                        .append(userAccount.getPassword())
                        .append("\n\nPlease note that this is a temporary "
                                + "password and you will have to reset the "
                                + "password once you sign in with this "
                                + "credentials.");
                mailUtil.setEmailBody(stringBuffer.toString());
                mailUtil.setEmailSubject("Registration Notice");
                mailUtil.sendEmail();

                CommonUtil.saveChanges(ecosystem);

            } else {
                WebOptionPane.showMessageDialog(null, errors, "Errors",
                        WebOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createPersonBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /* ---------------------------------------------------------------------- */
    /* Validates form
    
     Parameters: NONE
    
     Returns:
     1. errorText - STRING errors if there are any
     2. errorText - STRING blank if there are no errors
     */
    private String validateForm() {

        String errorText = "";

        try {

            int errorCount = 1;

            String enterpriseName = enterpriseNameText.getText().trim();
            String firstName = firstNameText.getText().trim();
            String lastName = lastNameText.getText().trim();
            String email = emailText.getText().trim();
            String userName = userNameText.getText().trim();
            String enterpriseType = (String) enterpriseTypeCombo
                    .getSelectedItem();
            Network network = (Network) networkCombo.getSelectedItem();

            if (enterpriseType.equals(Enterprise.ENTERPRISE_WAREHOUSE)) {
                if (!network.getWarehouseEnterpriseDirectory()
                        .getEnterpriseList().isEmpty()) {
                    errorText += errorCount + ". A warehouse is already added "
                            + "to this network. There can be only one "
                            + "warehouse for each network.";
                    errorCount++;
                }
            }

            if (enterpriseName.equals("")) {
                errorText += errorCount + ". Please enter the Enterprise "
                        + "Name\n";
                errorCount++;
            }

            if (firstName.equals("")) {
                errorText += errorCount + ". Please enter the First Name\n";
                errorCount++;
            }

            if (lastName.equals("")) {
                errorText += errorCount + ". Please enter the Last Name\n";
                errorCount++;
            }

            if (email.equals("")) {
                errorText += errorCount + ". Please enter the email ID\n";
                errorCount++;
            } else if (!CommonUtil.isEmailValid(email)) {
                errorText += errorCount + ". Invalid email ID\n";
                errorCount++;
            } else if (CommonUtil.exists(email, Constants.EXISTS_EMAIL,
                    ecosystem.getMasterPersonDirectory())) {
                errorText += errorCount + ". A user is already registered with "
                        + "this email ID\n";
                errorCount++;
            }

            if (userName.equals("")) {
                errorText += errorCount + ". Please enter the username\n";
                errorCount++;
            } else if (!CommonUtil.isUsernameValid(userName)) {
                errorText += errorCount + ". Invalid username. Make sure your "
                        + "username has 5-15 characters and only contain _, - "
                        + "or . as special characters\n";
                errorCount++;
            } else if (CommonUtil.exists(userName, Constants.EXISTS_USERNAME,
                    ecosystem.getMasterPersonDirectory())) {
                errorText += errorCount + ". username is already used.";
                errorCount++;
            }

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured\n" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        } finally {
            return errorText;
        }

    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEnterpriseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEnterpriseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEnterpriseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEnterpriseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateEnterpriseDialog dialog
                        = new CreateEnterpriseDialog(new javax.swing.JFrame(),
                                true, ecosystem, manageEnterprisePanel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton cancelBtn;
    private com.alee.laf.button.WebButton createPersonBtn;
    private com.alee.laf.text.WebTextField emailText;
    private com.alee.laf.text.WebTextField enterpriseNameText;
    private com.alee.laf.combobox.WebComboBox enterpriseTypeCombo;
    private com.alee.laf.text.WebTextField firstNameText;
    private com.alee.laf.text.WebTextField lastNameText;
    private com.alee.laf.combobox.WebComboBox networkCombo;
    private com.alee.laf.text.WebTextField userNameText;
    private com.alee.laf.label.WebLabel webLabel1;
    private com.alee.laf.label.WebLabel webLabel2;
    private com.alee.laf.label.WebLabel webLabel3;
    private com.alee.laf.label.WebLabel webLabel4;
    private com.alee.laf.label.WebLabel webLabel5;
    private com.alee.laf.label.WebLabel webLabel6;
    private com.alee.laf.label.WebLabel webLabel7;
    private com.alee.laf.label.WebLabel webLabel8;
    private com.alee.extended.label.WebMultiLineLabel webMultiLineLabel1;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    // End of variables declaration//GEN-END:variables
}
