/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.phmis.userinterface.enterpriseadmin;

import com.alee.laf.optionpane.WebOptionPane;
import com.neu.phmis.business.Ecosystem;
import com.neu.phmis.business.enterprise.Enterprise;
import com.neu.phmis.business.enterprise.HospitalEnterprise;
import com.neu.phmis.business.enterprise.SupplierEnterprise;
import com.neu.phmis.business.enterprise.WarehouseEnterprise;
import com.neu.phmis.business.organization.Organization;
import com.neu.phmis.business.organization.ProductOrganization;
import com.neu.phmis.business.organization.SalesOrganization;
import com.neu.phmis.business.user.Person;
import com.neu.phmis.business.util.CommonUtil;
import com.neu.phmis.userinterface.LoginPanel;
import com.neu.phmis.userinterface.MainFrame;
import com.neu.phmis.userinterface.doctor.ManageSchedulePanel;
import com.neu.phmis.userinterface.systemadmin.ChangePasswordPanel;

/**
 *
 * @author Vineet
 */
public class EnterpriseAdminDashboardPanel extends javax.swing.JPanel {

    private Ecosystem ecosystem;
    private Enterprise enterprise;
    private Person person;

    /**
     * Creates new form SupplierAdminWorkAreaPanel
     */
    public EnterpriseAdminDashboardPanel(Person person) {

        initComponents();

        ecosystem = Ecosystem.getInstance();
        this.person = person;
        enterprise = person.getEnterprise();

        if (enterprise instanceof HospitalEnterprise) {
            scheduleBtn.setVisible(true);
            resourceBtn.setVisible(true);
            inventoryBtn.setVisible(false);
            productsBtn.setVisible(false);
            ordersBtn.setVisible(false);
        } else if (enterprise instanceof WarehouseEnterprise) {
            scheduleBtn.setVisible(false);
            resourceBtn.setVisible(false);
            inventoryBtn.setVisible(true);
            productsBtn.setVisible(false);
            ordersBtn.setVisible(false);
        } else if (enterprise instanceof SupplierEnterprise) {
            scheduleBtn.setVisible(false);
            resourceBtn.setVisible(false);
            inventoryBtn.setVisible(false);
            productsBtn.setVisible(true);
            ordersBtn.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abstractButtonLU1 = new com.alee.managers.language.updaters.AbstractButtonLU();
        webPanel1 = new com.alee.laf.panel.WebPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        webPanel2 = new com.alee.laf.panel.WebPanel();
        logoutBtn = new com.alee.laf.button.WebButton();
        manageUserBtn = new com.alee.laf.button.WebButton();
        scheduleBtn = new com.alee.laf.button.WebButton();
        resourceBtn = new com.alee.laf.button.WebButton();
        inventoryBtn = new com.alee.laf.button.WebButton();
        productsBtn = new com.alee.laf.button.WebButton();
        ordersBtn = new com.alee.laf.button.WebButton();
        myAccountBtn = new com.alee.laf.button.WebButton();
        supplierContainer = new com.alee.laf.panel.WebPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        logoutBtn.setForeground(new java.awt.Color(0, 0, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        manageUserBtn.setForeground(new java.awt.Color(0, 0, 255));
        manageUserBtn.setText("Users");
        manageUserBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserBtnActionPerformed(evt);
            }
        });

        scheduleBtn.setForeground(new java.awt.Color(0, 0, 255));
        scheduleBtn.setText("Schedules");
        scheduleBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });

        resourceBtn.setForeground(new java.awt.Color(0, 0, 255));
        resourceBtn.setText("Resource");
        resourceBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resourceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceBtnActionPerformed(evt);
            }
        });

        inventoryBtn.setForeground(new java.awt.Color(0, 0, 255));
        inventoryBtn.setText("Inventory");
        inventoryBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });

        productsBtn.setForeground(new java.awt.Color(0, 0, 255));
        productsBtn.setText("Products");
        productsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBtnActionPerformed(evt);
            }
        });

        ordersBtn.setForeground(new java.awt.Color(0, 0, 255));
        ordersBtn.setText("Orders");
        ordersBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ordersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBtnActionPerformed(evt);
            }
        });

        myAccountBtn.setForeground(new java.awt.Color(0, 0, 255));
        myAccountBtn.setText("Settings");
        myAccountBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout webPanel2Layout = new javax.swing.GroupLayout(webPanel2);
        webPanel2.setLayout(webPanel2Layout);
        webPanel2Layout.setHorizontalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(scheduleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(resourceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(inventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(productsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(ordersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(myAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        webPanel2Layout.setVerticalGroup(
            webPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resourceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(webPanel2);

        supplierContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(supplierContainer);

        webPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(webPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed

        try {
            CommonUtil.saveChanges(ecosystem);
            LoginPanel loginPanel
                    = new LoginPanel(MainFrame.mainFrame.getContainer(), ecosystem);
            CommonUtil.insertNewPanel(MainFrame.mainFrame.getContainer(),
                    "Login Panel", loginPanel, this);
        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_logoutBtnActionPerformed

    private void manageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserBtnActionPerformed

        try {
            ManageUsersPanel manageUsersPanel
                    = new ManageUsersPanel(enterprise);
            CommonUtil.insertNewPanel(supplierContainer, "Manage User Panel",
                    manageUsersPanel, null);
        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_manageUserBtnActionPerformed

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed

        try {

            ViewSchedulePanel viewSchedulePanel
                    = new ViewSchedulePanel((HospitalEnterprise) enterprise);
            CommonUtil.insertNewPanel(supplierContainer, "Manage Schedule Panel",
                    viewSchedulePanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_scheduleBtnActionPerformed

    private void resourceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceBtnActionPerformed

        try {

            ViewResourcesPanel viewResourcesPanel
                    = new ViewResourcesPanel((HospitalEnterprise) enterprise);
            CommonUtil.insertNewPanel(supplierContainer, "Manage Resource Panel",
                    viewResourcesPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_resourceBtnActionPerformed

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed

        try {

            ViewInventoryItemsPanel viewInventoryItemsPanel
                    = new ViewInventoryItemsPanel(
                            (WarehouseEnterprise) enterprise);
            CommonUtil.insertNewPanel(supplierContainer, "View Inventory Panel",
                    viewInventoryItemsPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_inventoryBtnActionPerformed

    private void productsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBtnActionPerformed

        try {

            ViewProductsPanel viewProductsPanel
                    = new ViewProductsPanel((ProductOrganization) enterprise
                            .getOrganization(Organization.ORGANIZATION_PRODUCT));
            CommonUtil.insertNewPanel(supplierContainer, "View Products Panel",
                    viewProductsPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_productsBtnActionPerformed

    private void ordersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBtnActionPerformed

        try {

            ViewSalesOrdersPanel viewSalesOrdersPanel
                    = new ViewSalesOrdersPanel((SupplierEnterprise) enterprise);
            CommonUtil.insertNewPanel(supplierContainer, "View Orders Panel",
                    viewSalesOrdersPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ordersBtnActionPerformed

    private void myAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccountBtnActionPerformed

        try {

            ChangePasswordPanel changePasswordPanel
                    = new ChangePasswordPanel(ecosystem, person);
            CommonUtil.insertNewPanel(supplierContainer, "Settings",
                    changePasswordPanel, null);

        } catch (Exception e) {
            WebOptionPane.showMessageDialog(null,
                    "Some Unexpected Error Occured" + e.getMessage(), "Error",
                    WebOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_myAccountBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.managers.language.updaters.AbstractButtonLU abstractButtonLU1;
    private com.alee.laf.button.WebButton inventoryBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private com.alee.laf.button.WebButton logoutBtn;
    private com.alee.laf.button.WebButton manageUserBtn;
    private com.alee.laf.button.WebButton myAccountBtn;
    private com.alee.laf.button.WebButton ordersBtn;
    private com.alee.laf.button.WebButton productsBtn;
    private com.alee.laf.button.WebButton resourceBtn;
    private com.alee.laf.button.WebButton scheduleBtn;
    private com.alee.laf.panel.WebPanel supplierContainer;
    private com.alee.laf.panel.WebPanel webPanel1;
    private com.alee.laf.panel.WebPanel webPanel2;
    // End of variables declaration//GEN-END:variables
}
